### ISSUE TITLE
Assertion failure due to failing String conversion

### ISSUE THREAD

**Issue by ScruffR** [JeremyProffit/EchoPhotonBridge#12]
As outlined in the comment for #10 there is an issue in `void EchoPhotonBridge::_updateDeviceConfigs()` (and potentially in other places too)
```
echoDeviceConfigsV2 += "{\"name\":\"" + _v2devices[i].name + "\",\"type\":" + _v2devices[i].type + "}";
```
For some reason the implicit typecasting for `_v2devices[i].type` to `String` fails and causes `_echoDeviceCountV2` to be overwritten and consequently causing a memory prohibited memory access.

This minor change solves that particular issue.
```
echoDeviceConfigsV2 += "{\"name\":\"" + _v2devices[i].name + "\",\"type\":" + String(_v2devices[i].type) + "}";
```

Test code to provoke the Assertion Fault (tested with 1.2.0-beta.1 but probably present before)

```
#include "EchoPhotonBridge.h"

EchoPhotonBridge *epb;
int functionOnOffD7(int device, bool onOff, String rawParameters)
{
    digitalWrite(D7, (onOff) ? HIGH : LOW);
}
int functionOnOffRGB(int device, bool onOff, String rawParameters)
{
    RGB.control(onOff);
}

void setup()
{
    pinMode(D7, OUTPUT);
    epb = new EchoPhotonBridge();
    epb->addEchoDeviceV2OnOff("Photon Light", &functionOnOffD7);  // still OK
    epb->addEchoDeviceV2OnOff("Photon RGB", &functionOnOffRGB); // causes the SOS+10
}
```

BTW, is it intentional to use `.name` for the `type` field?
```
echoDeviceConfigsV3 += "{\"name\":\"" + _v3devices[i].name + "\",\"type\":" + _v3devices[i].name + "}";
```
If this also was supposed to be `_v3devices[i].type` then that should probably also be explicitly cast into `String`

**Comment by JeremyProffitt** [comment]
Updated in 0.7.5.  Please validate if you get a moment.  Thanks for the heads up.
