### ISSUE TITLE
Support for other languages?

### ISSUE THREAD

**Issue by ScruffR** [JeremyProffit/EchoPhotonBridge#4]
Since Amazon is patronising me into only selecting skills that are available for the ***local*** language - which is German in my case - I can't use your bridge as it isn't listed as available skill.

The joke with that is that Smart Home Skills are actually available in German so no risk in your skill not working but Amazon still insists in not allowing to change my language to English US, select the skill and then revert back to German.

BTW, I'd prefer speaking English but then I'm not allowed to add skills.

**Comment by amandus99** [comment]
Any chance that you will publish the skill to the German language? Is there something we could help to bring it to the German store? As far as I understood there is no need for local utterances as they are already build in for smart home skills?

**Comment by ScruffR** [comment]
@JeremyProffitt, any update on this?
I've seen some other member in the community who seems to have tackled the multi-lingual approach, but your skill seems much easier and flexible.

**Comment by JeremyProffitt** [comment]
I've done some checking, because this utilizes the Particle oAuth which does not support multiple call back URL's it's impossible to implement multi-region / multiple language support.
