### ISSUE TITLE
Support for time (hours, minutes, seconds) as a value

### ISSUE THREAD

**Issue by Forgvn77** [JeremyProffit/EchoPhotonBridge#5]
Would you be able to support time as a get or set value for a device function?  I would like to use it to return something like time remaining.  Thanks!

**Comment by JeremyProffitt** [comment]
No because Amazon's Home Automation Framework does not support that, you would have to write a custom Amazon Application.  But you can get time from NTP server once a day and keep time through out the day with MILLIS()
