### ISSUE TITLE
Alexa doesn't appear to trigger color function if color is "Purple"

### ISSUE THREAD

**Issue by dereksan** [JeremyProffit/EchoPhotonBridge#7]
I have a device that implements epb.addEchoDeviceV2Color(deviceName, &functionColor); -- It works fantastic... Except... For if I try to change color to Purple. I added some publish statements, and despite Alexa saying "OK", functionColor is never called. Works great for every other color.

**Comment by JeremyProffitt** [comment]
Purple is due to the hue to rgb conversion used.  This will be changed in the new library for v3 if I ever get around to writing it.
