### ISSUE TITLE
Could not find PHOTON device

### ISSUE THREAD

**Issue by jasonwangchaoshan** [JeremyProffit/EchoPhotonBridge#9]
When I burned light_on_off to PHOTON, ALEXA connected to Alexa apps, opened ENABLE SKIIL, but could not find PHOTON to control LED.

**Comment by JeremyProffitt** [comment]
Did you ask "Alexa, discover devices" to have alexa find the new device?

**Comment by jasonwangchaoshan** [comment]
Yes。
I also found no equipment in alexa-->home-->Skills-->Your Skill-->smart Home-->device-->DISCOVER？
think you！

**Comment by JeremyProffitt** [comment]
Can you please post your code?

**Comment by JeremyProffitt** [comment]
And are you seeing anything in your console when you check the functions?
